# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20170312_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
